/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.table.DefaultTableModel;
import models.*;
/**
 *
 * @author TUF
 */
public class MenuUtama extends javax.swing.JFrame {
    private int userId;
    /**
     * Creates new form MenuUtama
     */
    public MenuUtama(int userId) {
        initComponents();
        this.userId = userId;
        Utama utama = new Utama();
        List<CrudEdit> brgList = CrudEdit.getAllBrg();
        loadBrg(brgList);
    }

    MenuUtama() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gSorting = new javax.swing.ButtonGroup();
        pMenuUtama = new javax.swing.JPanel();
        pNavbar = new javax.swing.JPanel();
        bPemasok = new javax.swing.JButton();
        bHome = new javax.swing.JButton();
        inventarisBarang = new javax.swing.JLabel();
        bBarang = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taBarang = new javax.swing.JTable();
        sortir = new javax.swing.JLabel();
        tSearch = new javax.swing.JTextField();
        search = new javax.swing.JLabel();
        bSearch = new javax.swing.JButton();
        cSort = new javax.swing.JComboBox<>();
        filter = new javax.swing.JLabel();
        cFilter = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pMenuUtama.setBackground(new java.awt.Color(0, 153, 153));

        pNavbar.setBackground(new java.awt.Color(102, 193, 196));
        pNavbar.setPreferredSize(new java.awt.Dimension(750, 60));

        bPemasok.setText("Pemasok");
        bPemasok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPemasokActionPerformed(evt);
            }
        });

        bHome.setText("Home");
        bHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHomeActionPerformed(evt);
            }
        });

        inventarisBarang.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        inventarisBarang.setText("INVENTARIS BARANG");

        bBarang.setText("Barang");
        bBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBarangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pNavbarLayout = new javax.swing.GroupLayout(pNavbar);
        pNavbar.setLayout(pNavbarLayout);
        pNavbarLayout.setHorizontalGroup(
            pNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pNavbarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inventarisBarang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bBarang)
                .addGap(18, 18, 18)
                .addComponent(bPemasok)
                .addGap(18, 18, 18)
                .addComponent(bHome)
                .addGap(19, 19, 19))
        );
        pNavbarLayout.setVerticalGroup(
            pNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pNavbarLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(pNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bPemasok)
                    .addComponent(bHome)
                    .addComponent(inventarisBarang)
                    .addComponent(bBarang))
                .addContainerGap())
        );

        taBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Barang", "Nama Barang", "Tanggal Masuk", "Kategori", "Jumlah", "ID Pemasok"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(taBarang);

        sortir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sortir.setText("Sort Berdasarkan :");

        tSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tSearchActionPerformed(evt);
            }
        });

        search.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        search.setText("Search :");

        bSearch.setText("Search");
        bSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSearchActionPerformed(evt);
            }
        });

        cSort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID Barang Terkecil", "ID Barang Terbesar", "Nama Barang A/Z", "Nama Barang Z/A", "Jumlah Barang Terkecil", "Jumlah Barang Terbesar", "Tanggal Masuk Terbaru", "Tanggal Masuk Lama" }));
        cSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cSortActionPerformed(evt);
            }
        });

        filter.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        filter.setText("Filter Kategori :");

        cFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elektronik", "Furnitur", "ATK", "Kebersihan", "Keamanan", "Perangkat Jaringan" }));
        cFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cFilterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pMenuUtamaLayout = new javax.swing.GroupLayout(pMenuUtama);
        pMenuUtama.setLayout(pMenuUtamaLayout);
        pMenuUtamaLayout.setHorizontalGroup(
            pMenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pNavbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMenuUtamaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pMenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pMenuUtamaLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(pMenuUtamaLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(pMenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(search)
                            .addComponent(tSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bSearch))
                        .addGap(43, 43, 43)
                        .addGroup(pMenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sortir)
                            .addComponent(cSort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(pMenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(filter))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pMenuUtamaLayout.setVerticalGroup(
            pMenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMenuUtamaLayout.createSequentialGroup()
                .addComponent(pNavbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pMenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sortir)
                    .addComponent(search)
                    .addComponent(filter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pMenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cSort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(bSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pMenuUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pMenuUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void loadBrg(List<CrudEdit> brgList) {
        DefaultTableModel model = (DefaultTableModel) taBarang.getModel();
        model.setRowCount(0); // Clear existing data
        if (brgList.isEmpty()){
            model.addRow(new Object[]{"Tidak dapat ditemukan", "", "", "", "", ""});
        }else{
            for (CrudEdit brg : brgList) {
                Object[] row = {
                    brg.getIdBrg(),
                    brg.getNama(),
                    brg.getTgl(),
                    brg.getKategori(),
                    brg.getJml(),
                    brg.getIdPmsk()
                };
                model.addRow(row);
            }
        }
    }
    private void bPemasokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPemasokActionPerformed
        // TODO add your handling code here:
        MenuPemasok pmsk = new MenuPemasok(this.userId);
        pmsk.setVisible(true);
        pmsk.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_bPemasokActionPerformed

    private void tSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tSearchActionPerformed

    private void bSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSearchActionPerformed
        // TODO add your handling code here:
        String searchTerm = tSearch.getText().toLowerCase();
        // Mengecek apakah user memasukkan 2 karakter
        if (searchTerm.length() < 2) {
            javax.swing.JOptionPane.showMessageDialog(this, "Masukkan minimal 2 huruf untuk pencarian.", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Utama utama = new Utama();
        List<CrudEdit> brgList = CrudEdit.getAllBrg(); 

        // Filter berdasarkan ID Barang atau Nama Barang
        List<CrudEdit> filteredList = brgList.stream()
                .filter(brg -> brg.getIdBrg().toLowerCase().contains(searchTerm) || 
                               brg.getNama().toLowerCase().contains(searchTerm))
                .collect(Collectors.toList());

        loadBrg(filteredList);
    }//GEN-LAST:event_bSearchActionPerformed

    private void bBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBarangActionPerformed
        // TODO add your handling code here:
        MenuEdit edit = new MenuEdit(this.userId);
        edit.setVisible(true);
        edit.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_bBarangActionPerformed

    private void bHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHomeActionPerformed
        // TODO add your handling code here:
        MenuUtama utm = new MenuUtama(this.userId);
        utm.setVisible(true);
        utm.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_bHomeActionPerformed

    private void cSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cSortActionPerformed
        // TODO add your handling code here:
        Utama utama = new Utama();
        List<CrudEdit> brgList = CrudEdit.getAllBrg(); // Ambil semua barang

        switch (cSort.getSelectedItem().toString()) {
            case "ID Barang Terkecil":
                loadBrg(utama.sortByIdBrgTerkecil(brgList));
                break;
            case "ID Barang Terbesar":
                loadBrg(utama.sortByIdBrgTerbesar(brgList));
                break;
            case "Nama Barang A/Z":
                loadBrg(utama.sortByNamaBrgAZ(brgList));
                break;
            case "Nama Barang Z/A":
                loadBrg(utama.sortByNamaBrgZA(brgList));
                break;
            case "Jumlah Barang Terkecil":
                loadBrg(utama.sortByJumlahBrgTerkecil(brgList));
                break;
            case "Jumlah Barang Terbesar":
                loadBrg(utama.sortByJumlahBrgTerbesar(brgList));
                break;
            case "Tanggal Masuk Terbaru":
                loadBrg(utama.sortByTglMasukTerbaru(brgList));
                break;
            case "Tanggal Masuk Lama":
                loadBrg(utama.sortByTglMasukTerlama(brgList));
                break;
        }
    }//GEN-LAST:event_cSortActionPerformed

    private void cFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cFilterActionPerformed
        // TODO add your handling code here:
        String selectedKategori = cFilter.getSelectedItem().toString();
        Utama utama = new Utama();
        List<CrudEdit>brgList = CrudEdit.getAllBrg();
        List<CrudEdit> filteredList = utama.filterKtr(brgList, selectedKategori);
        loadBrg(filteredList);
    }//GEN-LAST:event_cFilterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBarang;
    private javax.swing.JButton bHome;
    private javax.swing.JButton bPemasok;
    private javax.swing.JButton bSearch;
    private javax.swing.JComboBox<String> cFilter;
    private javax.swing.JComboBox<String> cSort;
    private javax.swing.JLabel filter;
    private javax.swing.ButtonGroup gSorting;
    private javax.swing.JLabel inventarisBarang;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pMenuUtama;
    private javax.swing.JPanel pNavbar;
    private javax.swing.JLabel search;
    private javax.swing.JLabel sortir;
    private javax.swing.JTextField tSearch;
    private javax.swing.JTable taBarang;
    // End of variables declaration//GEN-END:variables
}
